apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app-container
          image: us.icr.io/ibm-daniels-workspace/cicd-casestudy-app
          imagePullPolicy: Always
          command: [ "echo", "K8 container SUCCESS" ]
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
