apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: de.icr.io/cicd-casestudy/ibm-node-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app
spec:
  selector:
    app: my-node-app
  type: NodePort
  ports:
    - nodePort: 31234
      protocol: TCP
      port: 3000
      targetPort: 3000
