apiVersion: v1
kind: Service
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  selector:
    app: my-node-app
  type: NodePort
  ports:
    - nodePort: 32100
      protocol: TCP
      port: 3000
      targetPort: 3000
