# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  setup-build-test:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ./app
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]
    steps:    
    - name: CHECK-OUT GIT REPOSITORY
      uses: actions/checkout@v2

    - name: USE NODEJS ${{ matrix.node-version }} - ${{ matrix.architecture }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies (npm)
      run: npm install
      env:
        CI: true

    - name: Start Node.JS (npm)
      run: npm run build --if-present
      env:
        CI: true

    - name: Node.JS Tests (npm)
      run: npm test
      env:
        CI: true
